// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: comm/meta.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OptionalBool int32

const (
	OptionalBool_NOT_SPECIFIED OptionalBool = 0
	OptionalBool_TRUE          OptionalBool = 1
	OptionalBool_FALSE         OptionalBool = 2
)

// Enum value maps for OptionalBool.
var (
	OptionalBool_name = map[int32]string{
		0: "NOT_SPECIFIED",
		1: "TRUE",
		2: "FALSE",
	}
	OptionalBool_value = map[string]int32{
		"NOT_SPECIFIED": 0,
		"TRUE":          1,
		"FALSE":         2,
	}
)

func (x OptionalBool) Enum() *OptionalBool {
	p := new(OptionalBool)
	*p = x
	return p
}

func (x OptionalBool) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OptionalBool) Descriptor() protoreflect.EnumDescriptor {
	return file_comm_meta_proto_enumTypes[0].Descriptor()
}

func (OptionalBool) Type() protoreflect.EnumType {
	return &file_comm_meta_proto_enumTypes[0]
}

func (x OptionalBool) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OptionalBool.Descriptor instead.
func (OptionalBool) EnumDescriptor() ([]byte, []int) {
	return file_comm_meta_proto_rawDescGZIP(), []int{0}
}

type LoadModuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dir  string `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LoadModuleRequest) Reset() {
	*x = LoadModuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModuleRequest) ProtoMessage() {}

func (x *LoadModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comm_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModuleRequest.ProtoReflect.Descriptor instead.
func (*LoadModuleRequest) Descriptor() ([]byte, []int) {
	return file_comm_meta_proto_rawDescGZIP(), []int{0}
}

func (x *LoadModuleRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *LoadModuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExtensionDefArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ident       string `protobuf:"bytes,1,opt,name=ident,proto3" json:"ident,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Reference   string `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	YinElement  bool   `protobuf:"varint,5,opt,name=yinElement,proto3" json:"yinElement,omitempty"`
}

func (x *ExtensionDefArg) Reset() {
	*x = ExtensionDefArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_meta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtensionDefArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionDefArg) ProtoMessage() {}

func (x *ExtensionDefArg) ProtoReflect() protoreflect.Message {
	mi := &file_comm_meta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionDefArg.ProtoReflect.Descriptor instead.
func (*ExtensionDefArg) Descriptor() ([]byte, []int) {
	return file_comm_meta_proto_rawDescGZIP(), []int{1}
}

func (x *ExtensionDefArg) GetIdent() string {
	if x != nil {
		return x.Ident
	}
	return ""
}

func (x *ExtensionDefArg) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExtensionDefArg) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *ExtensionDefArg) GetYinElement() bool {
	if x != nil {
		return x.YinElement
	}
	return false
}

type ExtensionDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ident       string             `protobuf:"bytes,1,opt,name=ident,proto3" json:"ident,omitempty"`
	Description string             `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Reference   string             `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	Status      int32              `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Args        []*ExtensionDefArg `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *ExtensionDef) Reset() {
	*x = ExtensionDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_meta_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtensionDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionDef) ProtoMessage() {}

func (x *ExtensionDef) ProtoReflect() protoreflect.Message {
	mi := &file_comm_meta_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionDef.ProtoReflect.Descriptor instead.
func (*ExtensionDef) Descriptor() ([]byte, []int) {
	return file_comm_meta_proto_rawDescGZIP(), []int{2}
}

func (x *ExtensionDef) GetIdent() string {
	if x != nil {
		return x.Ident
	}
	return ""
}

func (x *ExtensionDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExtensionDef) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *ExtensionDef) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ExtensionDef) GetArgs() []*ExtensionDefArg {
	if x != nil {
		return x.Args
	}
	return nil
}

type Extension struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ident   string   `protobuf:"bytes,1,opt,name=ident,proto3" json:"ident,omitempty"`
	Prefix  string   `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Keyword string   `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	ExtDef  string   `protobuf:"bytes,4,opt,name=extDef,proto3" json:"extDef,omitempty"`
	Args    []string `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *Extension) Reset() {
	*x = Extension{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_meta_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Extension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extension) ProtoMessage() {}

func (x *Extension) ProtoReflect() protoreflect.Message {
	mi := &file_comm_meta_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extension.ProtoReflect.Descriptor instead.
func (*Extension) Descriptor() ([]byte, []int) {
	return file_comm_meta_proto_rawDescGZIP(), []int{3}
}

func (x *Extension) GetIdent() string {
	if x != nil {
		return x.Ident
	}
	return ""
}

func (x *Extension) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Extension) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *Extension) GetExtDef() string {
	if x != nil {
		return x.ExtDef
	}
	return ""
}

func (x *Extension) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type Container struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ident       string       `protobuf:"bytes,1,opt,name=ident,proto3" json:"ident,omitempty"`
	Description string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Extensions  []*Extension `protobuf:"bytes,3,rep,name=extensions,proto3" json:"extensions,omitempty"`
	Definitions []*DataDef   `protobuf:"bytes,4,rep,name=definitions,proto3" json:"definitions,omitempty"`
	Config      OptionalBool `protobuf:"varint,14,opt,name=config,proto3,enum=pb.OptionalBool" json:"config,omitempty"`
	Mandatory   OptionalBool `protobuf:"varint,15,opt,name=mandatory,proto3,enum=pb.OptionalBool" json:"mandatory,omitempty"`
}

func (x *Container) Reset() {
	*x = Container{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_meta_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_comm_meta_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_comm_meta_proto_rawDescGZIP(), []int{4}
}

func (x *Container) GetIdent() string {
	if x != nil {
		return x.Ident
	}
	return ""
}

func (x *Container) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Container) GetExtensions() []*Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *Container) GetDefinitions() []*DataDef {
	if x != nil {
		return x.Definitions
	}
	return nil
}

func (x *Container) GetConfig() OptionalBool {
	if x != nil {
		return x.Config
	}
	return OptionalBool_NOT_SPECIFIED
}

func (x *Container) GetMandatory() OptionalBool {
	if x != nil {
		return x.Mandatory
	}
	return OptionalBool_NOT_SPECIFIED
}

type Leaf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ident       string       `protobuf:"bytes,1,opt,name=ident,proto3" json:"ident,omitempty"`
	Description string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Extensions  []*Extension `protobuf:"bytes,3,rep,name=extensions,proto3" json:"extensions,omitempty"`
	Config      OptionalBool `protobuf:"varint,14,opt,name=config,proto3,enum=pb.OptionalBool" json:"config,omitempty"`
	Mandatory   OptionalBool `protobuf:"varint,15,opt,name=mandatory,proto3,enum=pb.OptionalBool" json:"mandatory,omitempty"`
}

func (x *Leaf) Reset() {
	*x = Leaf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_meta_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Leaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leaf) ProtoMessage() {}

func (x *Leaf) ProtoReflect() protoreflect.Message {
	mi := &file_comm_meta_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leaf.ProtoReflect.Descriptor instead.
func (*Leaf) Descriptor() ([]byte, []int) {
	return file_comm_meta_proto_rawDescGZIP(), []int{5}
}

func (x *Leaf) GetIdent() string {
	if x != nil {
		return x.Ident
	}
	return ""
}

func (x *Leaf) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Leaf) GetExtensions() []*Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *Leaf) GetConfig() OptionalBool {
	if x != nil {
		return x.Config
	}
	return OptionalBool_NOT_SPECIFIED
}

func (x *Leaf) GetMandatory() OptionalBool {
	if x != nil {
		return x.Mandatory
	}
	return OptionalBool_NOT_SPECIFIED
}

type List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ident       string       `protobuf:"bytes,1,opt,name=ident,proto3" json:"ident,omitempty"`
	Description string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Extensions  []*Extension `protobuf:"bytes,3,rep,name=extensions,proto3" json:"extensions,omitempty"`
	Definitions []*DataDef   `protobuf:"bytes,4,rep,name=definitions,proto3" json:"definitions,omitempty"`
	Config      OptionalBool `protobuf:"varint,14,opt,name=config,proto3,enum=pb.OptionalBool" json:"config,omitempty"`
	Mandatory   OptionalBool `protobuf:"varint,15,opt,name=mandatory,proto3,enum=pb.OptionalBool" json:"mandatory,omitempty"`
}

func (x *List) Reset() {
	*x = List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_meta_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_comm_meta_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_comm_meta_proto_rawDescGZIP(), []int{6}
}

func (x *List) GetIdent() string {
	if x != nil {
		return x.Ident
	}
	return ""
}

func (x *List) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *List) GetExtensions() []*Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *List) GetDefinitions() []*DataDef {
	if x != nil {
		return x.Definitions
	}
	return nil
}

func (x *List) GetConfig() OptionalBool {
	if x != nil {
		return x.Config
	}
	return OptionalBool_NOT_SPECIFIED
}

func (x *List) GetMandatory() OptionalBool {
	if x != nil {
		return x.Mandatory
	}
	return OptionalBool_NOT_SPECIFIED
}

type LeafList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ident       string       `protobuf:"bytes,1,opt,name=ident,proto3" json:"ident,omitempty"`
	Description string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Extensions  []*Extension `protobuf:"bytes,3,rep,name=extensions,proto3" json:"extensions,omitempty"`
	Config      OptionalBool `protobuf:"varint,14,opt,name=config,proto3,enum=pb.OptionalBool" json:"config,omitempty"`
	Mandatory   OptionalBool `protobuf:"varint,15,opt,name=mandatory,proto3,enum=pb.OptionalBool" json:"mandatory,omitempty"`
}

func (x *LeafList) Reset() {
	*x = LeafList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_meta_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeafList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafList) ProtoMessage() {}

func (x *LeafList) ProtoReflect() protoreflect.Message {
	mi := &file_comm_meta_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafList.ProtoReflect.Descriptor instead.
func (*LeafList) Descriptor() ([]byte, []int) {
	return file_comm_meta_proto_rawDescGZIP(), []int{7}
}

func (x *LeafList) GetIdent() string {
	if x != nil {
		return x.Ident
	}
	return ""
}

func (x *LeafList) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LeafList) GetExtensions() []*Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *LeafList) GetConfig() OptionalBool {
	if x != nil {
		return x.Config
	}
	return OptionalBool_NOT_SPECIFIED
}

func (x *LeafList) GetMandatory() OptionalBool {
	if x != nil {
		return x.Mandatory
	}
	return OptionalBool_NOT_SPECIFIED
}

type DataDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to DefOneof:
	//
	//	*DataDef_Reference
	//	*DataDef_Leaf
	//	*DataDef_Container
	DefOneof isDataDef_DefOneof `protobuf_oneof:"def_oneof"`
}

func (x *DataDef) Reset() {
	*x = DataDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_meta_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDef) ProtoMessage() {}

func (x *DataDef) ProtoReflect() protoreflect.Message {
	mi := &file_comm_meta_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDef.ProtoReflect.Descriptor instead.
func (*DataDef) Descriptor() ([]byte, []int) {
	return file_comm_meta_proto_rawDescGZIP(), []int{8}
}

func (m *DataDef) GetDefOneof() isDataDef_DefOneof {
	if m != nil {
		return m.DefOneof
	}
	return nil
}

func (x *DataDef) GetReference() int32 {
	if x, ok := x.GetDefOneof().(*DataDef_Reference); ok {
		return x.Reference
	}
	return 0
}

func (x *DataDef) GetLeaf() *Leaf {
	if x, ok := x.GetDefOneof().(*DataDef_Leaf); ok {
		return x.Leaf
	}
	return nil
}

func (x *DataDef) GetContainer() *Container {
	if x, ok := x.GetDefOneof().(*DataDef_Container); ok {
		return x.Container
	}
	return nil
}

type isDataDef_DefOneof interface {
	isDataDef_DefOneof()
}

type DataDef_Reference struct {
	Reference int32 `protobuf:"varint,1,opt,name=reference,proto3,oneof"`
}

type DataDef_Leaf struct {
	Leaf *Leaf `protobuf:"bytes,2,opt,name=leaf,proto3,oneof"`
}

type DataDef_Container struct {
	Container *Container `protobuf:"bytes,3,opt,name=container,proto3,oneof"`
}

func (*DataDef_Reference) isDataDef_DefOneof() {}

func (*DataDef_Leaf) isDataDef_DefOneof() {}

func (*DataDef_Container) isDataDef_DefOneof() {}

type Module struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ident        string       `protobuf:"bytes,1,opt,name=ident,proto3" json:"ident,omitempty"`
	Description  string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Extensions   []*Extension `protobuf:"bytes,3,rep,name=extensions,proto3" json:"extensions,omitempty"`
	Definitions  []*DataDef   `protobuf:"bytes,4,rep,name=definitions,proto3" json:"definitions,omitempty"`
	Namespace    string       `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Prefix       string       `protobuf:"bytes,6,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Contact      string       `protobuf:"bytes,7,opt,name=contact,proto3" json:"contact,omitempty"`
	Organization string       `protobuf:"bytes,8,opt,name=organization,proto3" json:"organization,omitempty"`
	Reference    string       `protobuf:"bytes,9,opt,name=reference,proto3" json:"reference,omitempty"`
	Version      string       `protobuf:"bytes,10,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Module) Reset() {
	*x = Module{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_meta_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_comm_meta_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_comm_meta_proto_rawDescGZIP(), []int{9}
}

func (x *Module) GetIdent() string {
	if x != nil {
		return x.Ident
	}
	return ""
}

func (x *Module) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Module) GetExtensions() []*Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *Module) GetDefinitions() []*DataDef {
	if x != nil {
		return x.Definitions
	}
	return nil
}

func (x *Module) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Module) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Module) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *Module) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *Module) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *Module) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type DataDefHandle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DataDefHandle) Reset() {
	*x = DataDefHandle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_meta_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataDefHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDefHandle) ProtoMessage() {}

func (x *DataDefHandle) ProtoReflect() protoreflect.Message {
	mi := &file_comm_meta_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDefHandle.ProtoReflect.Descriptor instead.
func (*DataDefHandle) Descriptor() ([]byte, []int) {
	return file_comm_meta_proto_rawDescGZIP(), []int{10}
}

func (x *DataDefHandle) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_comm_meta_proto protoreflect.FileDescriptor

var file_comm_meta_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x39, 0x0a, 0x11, 0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x87, 0x01, 0x0a, 0x0f, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65,
	0x66, 0x41, 0x72, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x79, 0x69,
	0x6e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x79, 0x69, 0x6e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xa5, 0x01, 0x0a, 0x0c, 0x45,
	0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x66, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x61, 0x72, 0x67,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x74,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x66, 0x41, 0x72, 0x67, 0x52, 0x04, 0x61, 0x72,
	0x67, 0x73, 0x22, 0x7f, 0x0a, 0x09, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x18, 0x0a,
	0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x74, 0x44, 0x65,
	0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x78, 0x74, 0x44, 0x65, 0x66, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x72, 0x67, 0x73, 0x22, 0xfb, 0x01, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x0a, 0x65, 0x78, 0x74,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x65, 0x78,
	0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x0b, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x70, 0x62, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x52, 0x0b, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x2e, 0x0a, 0x09, 0x6d, 0x61, 0x6e, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x0f,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x09, 0x6d, 0x61, 0x6e, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x79, 0x22, 0xc7, 0x01, 0x0a, 0x04, 0x4c, 0x65, 0x61, 0x66, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x74, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x28, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x42,
	0x6f, 0x6f, 0x6c, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2e, 0x0a, 0x09, 0x6d,
	0x61, 0x6e, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x42, 0x6f, 0x6f, 0x6c,
	0x52, 0x09, 0x6d, 0x61, 0x6e, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x79, 0x22, 0xf6, 0x01, 0x0a, 0x04,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x0a,
	0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x0a, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x0b, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x52, 0x0b, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x2e, 0x0a, 0x09, 0x6d, 0x61, 0x6e, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x79, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x09, 0x6d, 0x61, 0x6e, 0x64, 0x61,
	0x74, 0x6f, 0x72, 0x79, 0x22, 0xcb, 0x01, 0x0a, 0x08, 0x4c, 0x65, 0x61, 0x66, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x0a, 0x65, 0x78, 0x74,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x65, 0x78,
	0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x2e, 0x0a, 0x09, 0x6d, 0x61, 0x6e, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x79, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x09, 0x6d, 0x61, 0x6e, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x79, 0x22, 0x85, 0x01, 0x0a, 0x07, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x12, 0x1e,
	0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x00, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1e,
	0x0a, 0x04, 0x6c, 0x65, 0x61, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70,
	0x62, 0x2e, 0x4c, 0x65, 0x61, 0x66, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x65, 0x61, 0x66, 0x12, 0x2d,
	0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x42, 0x0b, 0x0a,
	0x09, 0x64, 0x65, 0x66, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0xca, 0x02, 0x0a, 0x06, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a,
	0x0a, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x0b,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x66, 0x52, 0x0b,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x6f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x1f, 0x0a, 0x0d, 0x44, 0x61, 0x74, 0x61, 0x44,
	0x65, 0x66, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x2a, 0x36, 0x0a, 0x0c, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x4f, 0x54, 0x5f,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x54,
	0x52, 0x55, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x41, 0x4c, 0x53, 0x45, 0x10, 0x02,
	0x32, 0x3b, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x0a, 0x4c, 0x6f,
	0x61, 0x64, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f,
	0x61, 0x64, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comm_meta_proto_rawDescOnce sync.Once
	file_comm_meta_proto_rawDescData = file_comm_meta_proto_rawDesc
)

func file_comm_meta_proto_rawDescGZIP() []byte {
	file_comm_meta_proto_rawDescOnce.Do(func() {
		file_comm_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_comm_meta_proto_rawDescData)
	})
	return file_comm_meta_proto_rawDescData
}

var file_comm_meta_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_comm_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_comm_meta_proto_goTypes = []interface{}{
	(OptionalBool)(0),         // 0: pb.OptionalBool
	(*LoadModuleRequest)(nil), // 1: pb.LoadModuleRequest
	(*ExtensionDefArg)(nil),   // 2: pb.ExtensionDefArg
	(*ExtensionDef)(nil),      // 3: pb.ExtensionDef
	(*Extension)(nil),         // 4: pb.Extension
	(*Container)(nil),         // 5: pb.Container
	(*Leaf)(nil),              // 6: pb.Leaf
	(*List)(nil),              // 7: pb.List
	(*LeafList)(nil),          // 8: pb.LeafList
	(*DataDef)(nil),           // 9: pb.DataDef
	(*Module)(nil),            // 10: pb.Module
	(*DataDefHandle)(nil),     // 11: pb.DataDefHandle
}
var file_comm_meta_proto_depIdxs = []int32{
	2,  // 0: pb.ExtensionDef.args:type_name -> pb.ExtensionDefArg
	4,  // 1: pb.Container.extensions:type_name -> pb.Extension
	9,  // 2: pb.Container.definitions:type_name -> pb.DataDef
	0,  // 3: pb.Container.config:type_name -> pb.OptionalBool
	0,  // 4: pb.Container.mandatory:type_name -> pb.OptionalBool
	4,  // 5: pb.Leaf.extensions:type_name -> pb.Extension
	0,  // 6: pb.Leaf.config:type_name -> pb.OptionalBool
	0,  // 7: pb.Leaf.mandatory:type_name -> pb.OptionalBool
	4,  // 8: pb.List.extensions:type_name -> pb.Extension
	9,  // 9: pb.List.definitions:type_name -> pb.DataDef
	0,  // 10: pb.List.config:type_name -> pb.OptionalBool
	0,  // 11: pb.List.mandatory:type_name -> pb.OptionalBool
	4,  // 12: pb.LeafList.extensions:type_name -> pb.Extension
	0,  // 13: pb.LeafList.config:type_name -> pb.OptionalBool
	0,  // 14: pb.LeafList.mandatory:type_name -> pb.OptionalBool
	6,  // 15: pb.DataDef.leaf:type_name -> pb.Leaf
	5,  // 16: pb.DataDef.container:type_name -> pb.Container
	4,  // 17: pb.Module.extensions:type_name -> pb.Extension
	9,  // 18: pb.Module.definitions:type_name -> pb.DataDef
	1,  // 19: pb.Parser.LoadModule:input_type -> pb.LoadModuleRequest
	10, // 20: pb.Parser.LoadModule:output_type -> pb.Module
	20, // [20:21] is the sub-list for method output_type
	19, // [19:20] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_comm_meta_proto_init() }
func file_comm_meta_proto_init() {
	if File_comm_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_comm_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadModuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_meta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtensionDefArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_meta_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtensionDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_meta_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Extension); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_meta_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Container); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_meta_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Leaf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_meta_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_meta_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeafList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_meta_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_meta_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Module); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_meta_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataDefHandle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_comm_meta_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*DataDef_Reference)(nil),
		(*DataDef_Leaf)(nil),
		(*DataDef_Container)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comm_meta_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comm_meta_proto_goTypes,
		DependencyIndexes: file_comm_meta_proto_depIdxs,
		EnumInfos:         file_comm_meta_proto_enumTypes,
		MessageInfos:      file_comm_meta_proto_msgTypes,
	}.Build()
	File_comm_meta_proto = out.File
	file_comm_meta_proto_rawDesc = nil
	file_comm_meta_proto_goTypes = nil
	file_comm_meta_proto_depIdxs = nil
}
