name: GitHub Actions Demo

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Installing protoc-gen-go
        run: |
          go get -u google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

      - name: Generate code
        run: |
          ! test -d pb || rm -rf pb
          mkdir pb
          protoc \
            -I./proto \
            --plugin=protoc-gen-go-grpc=${HOME}/go/bin/protoc-gen-go-grpc \
            --plugin=protoc-gen-go=${HOME}/go/bin/protoc-gen-go \
            --go_out=. \
            --go-grpc_out=. \
            ./proto/freeconf/pb/*.proto

      - name: Build
        run: go build -v cmd/fc-lang/main.go
