name: GitHub Actions Demo

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Add Go dirs PATH
        run: |
          echo "${HOME}/go/bin:${PWD}/bin" >> $GITHUB_PATH

      - name: Installing protoc-gen-go
        run: make deps-go

      - name: Generate Go code
        run: make proto-go generate

      - name: Build
        run: |
          make bin/fc-lang

      - name: Test
        run: FC=LANG=go make test-go

      - name: Dist
        run: make dist-go

  # TODO: Figure out how to separate this into separate jobs. currently this
  # doesn't have access to source and likely not build output from go build
  # so i supposed i don't understand workflows just yet.  Until then, merge in
  # the python tasks after the go tasks
  #
  # python:
  #   needs: go
  #   runs-on: ubuntu-latest
  #   steps:

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: make deps-py

      - name: Generate Python code
        run: make proto-py

      - name: Test python to go
        run: make test-py

      - name: Test go to python via harness.py
        run: FC_LANG=python make test-go

      - name: Dist
        run: make dist-py

  # Push Release only when Python tasks succeed ok.

      - name: Setup release publisher plugin
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
              ./bin/fc-lang-*
              ./python/dist/freeconf*.whl
