name: GitHub Actions Demo

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Installing protoc-gen-go
        run: |
          go get github.com/golang/protobuf/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc   

      - name: Generate code
        run: |
          ! test -d pb || rm -rf pb
          mkdir pb
          protoc \
            -I./proto \
            --go_out=. \
            --go-grpc_out=. \
            ./proto/freeconf/pb/*.proto

      - name: Build
        run: go build -v cmd/fc-lang/main.go
