name: GitHub Actions Demo

on: [push]

jobs:

  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Add Go dirs PATH
        run: |
          echo "${HOME}/go/bin:${PWD}/bin" >> $GITHUB_PATH

      - name: Installing protoc-gen-go
        run: make deps-go

      - name: Generate Go code
        run: make proto-go generate

      - name: Build
        run: |
          make bin/fc-lang

      - name: Test
        run: FC=LANG=go make test-go

  python:
    needs: go
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: make deps-py

      - name: Generate Python code
        run: make proto-py

      - name: Test
        run: make test-py

      - name: Test from go
        run: FC_LANG=python make test-go

      - name: Dist
        run: make dist-py
